apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-runner
  namespace: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-demo
  template:
    metadata:
      labels:
        app: rbac-demo
    spec:
      serviceAccountName: demo-runner
      containers:
      - name: podmayhem
        image: securecorporation/infinity-k8s:podmayhem
